### ISSUE TITLE
Support for the FBV EXPRESS MKII?

### ISSUE THREAD

**Issue by Andreas-T** [kquann/FBV_MIDI#1]
Hi.
Very interesting project. Thank you for sharing.
I wonder if the RJ-45 protocol used in these controllers is the same as in the FBV EXPRESS MKII?
Specifically I am looking to repurpose the Express to be able to send custom Sysex strings to a Roland keyboard by toggling a footswitch (4 message string, 68 bytes total for each switch state). If I could add MIDI out functionality to the Express also it would be great (to avoid having to use a USB Host/MIDI Out converter).
Thoughts?
Thanks for your time.

**Comment by kquann** [comment]
Sorry for the late response. The Sysex protocol should be the same for the Express MkII, just with fewer buttons, though I have not tried it to confirm. The Python script could be easily modified to send a Sysex message
