### ISSUE TITLE
Fbv3 + Raspberry + Boss Katana

### ISSUE THREAD

**Issue by Rob-C89** [kquann/FBV_MIDI#2]
Hi, I was wondering if it was possible to adapt your work to connect the FBV3 to a Boss Katana using just a Raspberry Pi, therefore using only usb and not the Rj45. Do you think it will be possible?

**Comment by kquann** [comment]
Hi sorry for the late response. You could use an FBV connected directly over USB for that purpose as described here:
https://www.reddit.com/r/BossKatana/comments/msd597/controlling_the_katana_with_a_midi_controller/

However, MIDI implementation will be somewhat limited. This project (FBV_MIDI) sets out to make the FBV a more robust MIDI controller, though requires the use of the Arduino Sysex handler. Most likely, this will be more than you need if you are just looking to just control your Katana.
